# Generated by Django 4.1 on 2022-10-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShaRoSa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharosa',
            old_name='confrmpasswrd',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sharosa',
            old_name='password',
            new_name='passwrd',
        ),
    ]
