# Generated by Django 4.1 on 2022-10-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShaRoSa', '0002_rename_confrmpasswrd_sharosa_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('charge', models.IntegerField(max_length=4)),
            ],
        ),
    ]
