# Generated by Django 4.1 on 2022-10-10 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShaRoSa', '0003_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Bill',
        ),
    ]
